### PR TITLE
Shebang explicitly to python2

### PR DESCRIPTION
**Pull request by nagracks**
Without this it would not work on system where `python3` is the default python. Now it will explicitly look for `python2`

### CODE REVIEW

**Comment by cuongnv23** [comment]
Hi, 
This script is not tested on my `python3`, if you want to make this script more `python3`-ish, it needs more than changing shebang.

**Comment by nagracks** [comment]
I saying that this script would not work where the default python is
version 3 by that I mean on that system this script needs to call
python2 explicitly thats it. Thank you.

**Comment by cuongnv23** [comment]
ok, i understand. but if you change the shebang to `python3`, this script even doesn't work. If you want to change that shebang to `python3`, you need to do some extra works (which I don't have time to do now) to make it run on your system .

**Comment by cuongnv23** [comment]
and i'd love to see the way you make it more `python3`-ish ;) thanks for making contribution to my scripts :)

**Comment by nagracks** [comment]
close #2

**Pull request closed without merging**
